---

- hosts: localhost
  connection: local

  tasks:
    - name: install base brews
      homebrew: name={{item}} state=latest
      with_items:
        - node
        - bash-completion
        - apm-bash-completion
        - brew-cask-completion
        - docker-completion
        - docker-compose-completion
        - tmux
        - powerline
        - coreutils
        - autojump
        - fzf
        - fish
        - git
        - git-extras
        - wget
        - pwgen
        - xmlstarlet
        - htop-osx
        - siege
        - watch
        - rsync
        - maven
        - gradle
        - httpie
        - osxfuse
        - sshfs
        - ack
        - ag
        - wget
        - python3
        - go
        - docker-engine
        - docker-compose
        - uchardet
        - graphviz
    - name: install personal cask applications
      homebrew_cask: name={{item}} state=present
      with_items:
        - google-chrome
        - keepingyouawake
        - atom
        - bartender
        - hammerspoon
        - grandperspective
        - qlstephen
        - sourcetree
        - google-chrome
        - firefox
        - adium
        - skype
        - java8
        - p4merge
        - yed
        - jumpcut
        - gfxcardstatus
        - istat-menus
        - iterm2
        - vlc
        - jing
        - devonthink-pro-office
        - slack
        - macvim
        - onepassword
        - dropbox
        - google-drive
        - evernote
        - alfred
        - spotify
        - virtualbox
        - vagrant
        - secrets
        - launchrocket
        - istumbler
        - visualvm
        - scansnap-manager-s1300
        - 0xed
        - calibre
        - zeplin
    - name: create ssh directory
      become: yes
      file:
        path: "{{item}}"
        state: directory
        owner: root
        group: wheel
        mode: 0777
      with_items:
        - /etc/ssh
    - name: personal ssh config
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh_config
    - name: personal ssh config in another location
      become: yes
      copy:
        src: files/ssh_config
        dest: /etc/ssh/ssh_config
    - name: add to sudoers without password
      become: yes
      lineinfile: >
        dest=/etc/sudoers
        regexp="{{ item.regexp }}"
        line="{{ item.line }}"
        state=present
        create=true
      with_items:
        - { regexp: '^ryan', line: 'ryan ALL=(ALL) NOPASSWD: ALL' }

  roles:
    - profile-all
    - profile-developer

  vars:
    - computername: rcrumley
    - git_user_name: Ryan Crumley
    - git_user_email: crumley@gmail.com
    - osx_defaults:
      - domain: 'com.apple.dock'
        key: 'minimize-to-application'
        type: integer
        value: 1
      - domain: 'com.apple.dock'
        key: 'show-process-indicators'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'NSTableViewDefaultSizeMode'
        type: integer
        value: 1
      - domain: 'com.apple.screencapture'
        key: 'type'
        type: string
        value: png
      - domain: 'NSGlobalDomain'
        key: 'KeyRepeat'
        type: integer
        value: 2
      - domain: 'NSGlobalDomain'
        key: 'InitialKeyRepeat'
        type: integer
        value: 15
      - domain: 'com.apple.menuextra.clock'
        key: 'DateFormat'
        type: string
        value: EEE MMM d  HH:mm
      - domain: 'com.apple.menuextra.battery'
        key: 'ShowPercent'
        type: string
        value: 'YES'
      - domain: 'com.apple.finder'
        key: 'FXPreferredViewStyle'
        type: string
        value: "clmv"
      - domain: 'NSGlobalDomain'
        key: 'NSNavPanelExpandedStateForSaveMode'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'PMPrintingExpandedStateForPrint'
        type: boolean
        value: true
      - domain: 'com.apple.dock'
        key: 'tilesize'
        type: float
        value: 32
      - domain: 'com.apple.dock'
        key: 'autohide-time-modifier'
        type: int
        value: 0
      - domain: 'com.apple.dock'
        key: 'autohide-delay'
        type: int
        value: 0
      - domain: 'NSGlobalDomain'
        key: 'NSQuitAlwaysKeepsWindows'
        type: boolean
        value: false
      - domain: 'com.apple.desktopservices'
        key: 'DSDontWriteNetworkStores'
        type: boolean
        value: true
      - domain: 'com.apple.print.PrintingPrefs'
        key: 'Quit When Finished'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeInternalDebugMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'IncludeDevelopMenu'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'WebKitDeveloperExtrasEnabledPreferenceKey'
        type: boolean
        value: true
      - domain: 'com.apple.Safari'
        key: 'com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled'
        type: boolean
        value: true
      - domain: 'NSGlobalDomain'
        key: 'WebKitDeveloperExtras'
        type: boolean
        value: true
